# Generated by Django 4.2.16 on 2025-06-04 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 5, 22, 8, 994927)),
        ),
    ]
