# Generated by Django 4.2.16 on 2025-06-04 05:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_alter_form_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name'], 'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Items'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-week'], 'verbose_name': 'Food Form', 'verbose_name_plural': 'Food Forms'},
        ),
        migrations.AlterModelOptions(
            name='lunchform',
            options={'verbose_name': 'Lunch Form', 'verbose_name_plural': 'Lunch Forms'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['weekday'], 'verbose_name': 'Daily Option', 'verbose_name_plural': 'Daily Options'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Food Order', 'verbose_name_plural': 'Food Orders'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['weekday'], 'verbose_name': 'Daily Reservation', 'verbose_name_plural': 'Daily Reservations'},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'Food Selection', 'verbose_name_plural': 'Food Selections'},
        ),
        migrations.AlterModelOptions(
            name='snacksform',
            options={'verbose_name': 'Snacks Form', 'verbose_name_plural': 'Snacks Forms'},
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this order was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.CharField(help_text='URL to food item image', max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(help_text='Name of the food item', max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in PHP'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('SNACKS', 'Snacks')], default='LUNCH', help_text='Type of food item', max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether this form is currently active for ordering'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='When this form was created'),
        ),
        migrations.AlterField(
            model_name='form',
            name='options',
            field=models.ManyToManyField(help_text='Food options available for each day of the week', to='forms.option'),
        ),
        migrations.AlterField(
            model_name='form',
            name='week',
            field=models.CharField(help_text='Week identifier (e.g., 2024-W01)', max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='food_items',
            field=models.ManyToManyField(help_text='Food items available for this day', to='forms.fooditem'),
        ),
        migrations.AlterField(
            model_name='option',
            name='weekday',
            field=models.CharField(choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thursday'), ('5', 'friday')], help_text='Day of the week', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='form',
            field=models.ForeignKey(help_text='The form this order was placed on', on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether this order has been fully paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(help_text='User who placed this order', on_delete=django.db.models.deletion.CASCADE, to='forms.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reservations',
            field=models.ManyToManyField(help_text='Daily reservations included in this order', related_name='order', to='forms.reservation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_paid',
            field=models.IntegerField(default=0, help_text='Total amount for this order in PHP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, help_text='Department/division', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Full name of the user', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, help_text='Job title/role', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='Associated Django user account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False, help_text='Whether this reservation has been paid for'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='weekday',
            field=models.CharField(choices=[('1', 'monday'), ('2', 'tuesday'), ('3', 'wednesday'), ('4', 'thursday'), ('5', 'friday')], help_text='Day of the week for this reservation', max_length=3),
        ),
        migrations.AlterField(
            model_name='selection',
            name='food_item',
            field=models.ForeignKey(help_text='The selected food item', on_delete=django.db.models.deletion.CASCADE, to='forms.fooditem'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Number of items ordered'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='reservation',
            field=models.ForeignKey(help_text='The reservation this selection belongs to', on_delete=django.db.models.deletion.CASCADE, to='forms.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('reservation', 'food_item')},
        ),
    ]
