# Generated by Django 4.2.16 on 2024-11-18 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_form_created_at_alter_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('SNACKS', 'Snacks')], default='LUNCH', max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 13, 25, 22, 541814)),
        ),
    ]
