# Generated by Django 5.0 on 2024-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_fooditem_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='friday',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='thursday',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='tuesday',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='wednesday',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
