# Generated by Django 4.2.16 on 2024-11-18 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_lunchform_snacksform_remove_form_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LunchForm',
        ),
        migrations.DeleteModel(
            name='SnacksForm',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 13, 47, 33, 715075)),
        ),
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.CharField(choices=[('LUNCH', 'Lunch'), ('SNACKS', 'Snacks')], default='LUNCH', max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 13, 47, 33, 715685)),
        ),
    ]
