# Generated by Django 5.0 on 2024-01-17 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_form_active_alter_form_created_at_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='food_item',
            field=models.ManyToManyField(to='forms.fooditem'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 18, 8, 44, 682670)),
        ),
    ]
