# Generated by Django 4.2.16 on 2024-11-18 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_delete_lunchform_delete_snacksform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.form')),
            ],
            bases=('forms.form',),
        ),
        migrations.CreateModel(
            name='SnacksForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.form')),
            ],
            bases=('forms.form',),
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='type',
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 13, 50, 56, 504800)),
        ),
    ]
