# Generated by Django 5.0 on 2024-01-17 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_rename_food_item_option_food_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='food_items',
            new_name='food_item',
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 18, 14, 3, 797034)),
        ),
        migrations.AlterField(
            model_name='option',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday')], max_length=3),
        ),
    ]
