# Generated by Django 4.2.16 on 2024-11-23 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_lunchform_snacksform_remove_fooditem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 14, 12, 28, 746057)),
        ),
    ]
