# Generated by Django 5.0 on 2024-01-17 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_rename_food_items_option_food_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='food_item',
            new_name='food_items',
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 18, 14, 35, 602821)),
        ),
    ]
