# Generated by Django 5.0 on 2024-01-17 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_remove_profile_email_alter_form_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reservations',
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 20, 30, 38, 674674)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservations', models.ManyToManyField(to='forms.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ManyToManyField(to='forms.order'),
        ),
    ]
