# Generated by Django 5.0 on 2024-01-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_remove_profile_reservations_alter_form_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='order',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 20, 35, 3, 5429)),
        ),
    ]
