# Generated by Django 5.0 on 2024-01-17 12:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_rename_order_profile_orders_alter_form_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='form',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 20, 38, 57, 611065)),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 20, 38, 57, 610068)),
        ),
    ]
